[package]
name = "todp"
version = "0.1.0"
edition = "2024"
description = "a todo app which builds a json file per folder"
homepage = "https://github.com/prt009/todp"
documentation = "https://github.com/prt009/todp/wiki"
license = "MIT"

[dependencies]
serde = { version = "1.0.229", features = ["derive"] }
serde_json = "1.0.151"

[profile.release]
opt-level = "z"
lto = true
panic = "abort"
codegen-units = 1
strip = true   
